# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='secret',
            name='like',
        ),
        migrations.AddField(
            model_name='secret',
            name='likeSecret',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like', to='login.Secret'),
        ),
    ]
